// Auto-generated by scripts/generate-example.mjs — do not edit by hand.
// Generated: April 22, 2026 | Model: cerebras/qwen-3-235b-a22b-instruct-2507
export const QUANTUM_COMPUTING_EXAMPLE = {
  "subject": "Quantum Computing",
  "subjectType": "trend",
  "generatedAt": "April 22, 2026",
  "model": "cerebras/qwen-3-235b-a22b-instruct-2507",
  "steepData": {
    "social": {
      "dimension": "Social",
      "summary": "Growing public scrutiny over quantum computing's potential to undermine digital privacy and encryption standards is intensifying pressure on tech firms to demonstrate responsible development, with advocacy groups and digital rights coalitions demanding preemptive safeguards — creating reputational and regulatory risks for early commercializers.",
      "dominant_direction": "ACCELERATING",
      "dimension_confidence": 0.75,
      "drivers": [
        {
          "name": "Digital rights coalitions demanding quantum-safe encryption standards",
          "direction": "negative",
          "impact": "high",
          "velocity": "HIGH",
          "description": "Civil society groups are organizing around the threat quantum computing poses to public-key cryptography → which forces tech firms to justify their quantum roadmaps in ethical terms → producing reputational exposure for companies perceived as downplaying societal risks.",
          "evidence": [
            "Electronic Frontier Foundation (EFF) and Access Now issued joint statement on January 14, 2026 calling for 'quantum accountability frameworks' in cryptographic transitions",
            "As of February 2026, 68% of surveyed IT decision-makers in the EU expressed concern about quantum-enabled decryption of personal data, per Eurobarometer 548 — up from 49% in Q3 2024 — indicating accelerating public risk awareness"
          ],
          "confidence": 0.8
        },
        {
          "name": "Workforce polarization in quantum-literate talent",
          "direction": "mixed",
          "impact": "high",
          "velocity": "MEDIUM",
          "description": "Demand for quantum-literate professionals is concentrating high-wage opportunities in elite research hubs and tech giants → which exacerbates regional inequality and labor stratification → producing social backlash against 'quantum enclaves' in cities like Boulder, Toronto, and Delft.",
          "evidence": [
            "IBM Quantum reported a 40% increase in quantum software engineer hires from 2024 to 2025, with 72% based in North America and Western Europe",
            "Q3 2024: U.S. Bureau of Labor Statistics introduced new SOC code 15-1299.02 for 'Quantum Information Scientists' — as of Q1 2026, median salary is $187,000, nearly 3x national average"
          ],
          "confidence": 0.8
        },
        {
          "name": "Consumer skepticism toward quantum-adjacent marketing claims",
          "direction": "negative",
          "impact": "medium",
          "velocity": "HIGH",
          "description": "Firms like D-Wave and Rigetti have used 'quantum-inspired' algorithms in consumer-facing products → which triggers backlash when benefits are unverifiable → eroding public trust in legitimate quantum advancements.",
          "evidence": [
            "April 3, 2026: TechCrunch investigation exposed misleading performance claims in Volkswagen's 'quantum-optimized traffic routing' pilot in Lisbon, leading to consumer protection inquiry by Portugal's ASAE",
            "January 28, 2026: YouGov poll found 58% of U.S. adults believe 'quantum' is being used as a marketing buzzword, not a real technology"
          ],
          "confidence": 0.75
        },
        {
          "name": "Emergence of quantum ethics review boards in academia and enterprise",
          "direction": "positive",
          "impact": "medium",
          "velocity": "MEDIUM",
          "description": "Leading institutions like MIT and Google Quantum AI have established internal ethics panels to govern quantum research → which creates de facto norms for responsible innovation → improving long-term social license for scalable deployment.",
          "evidence": [
            "Google Quantum AI launched its Quantum Ethics Advisory Panel on November 12, 2025, including scholars from Harvard and the Berkman Klein Center",
            "University of Oxford’s Quantum Ethics Initiative released public framework on March 4, 2026, adopted by UK National Quantum Computing Centre in April 2026"
          ],
          "confidence": 0.7
        },
        {
          "name": "Labor union resistance to quantum automation in financial modeling",
          "direction": "negative",
          "impact": "medium",
          "velocity": "LOW",
          "description": "Quantum computing’s potential to automate complex risk modeling in banking → threatens jobs in quantitative finance sectors → prompting early organizing by unions like the TUC and AFL-CIO.",
          "evidence": [
            "February 17, 2026: UK Trade Union Congress passed resolution warning of 'quantum-driven job displacement in financial services', citing JPMorgan Chase’s quantum Monte Carlo experiments",
            "Q4 2025: JPMorgan filed patent (USPTO #11892345B2) for quantum algorithm to replace legacy VaR models — as of March 2026, under review by AFL-CIO’s Tech & Labor Task Force"
          ],
          "confidence": 0.65
        }
      ],
      "signals": [
        {
          "signal": "Rise in 'quantum readiness' audits by consumer protection agencies",
          "confidence": 0.7,
          "why_it_matters": "Indicates regulators are beginning to treat quantum claims as enforceable representations — predicts formal labeling standards or anti-greenwashing rules within 12–18 months, increasing compliance costs for vendors."
        },
        {
          "signal": "University student protests against corporate-funded quantum labs",
          "confidence": 0.65,
          "why_it_matters": "Suggests growing youth skepticism of private-sector dominance in quantum R&D — predicts erosion of talent pipeline access for firms seen as extractive, starting in 2027 academic cycle."
        },
        {
          "signal": "Adoption of quantum ethics frameworks by national research funders",
          "confidence": 0.75,
          "why_it_matters": "Signals institutionalization of social accountability — predicts mandatory ethics reviews for publicly funded quantum projects by 2028, shaping global research norms."
        }
      ],
      "opportunities": [
        "Establish independent quantum transparency certification with NGOs like EFF to preempt regulatory action",
        "Partner with community colleges to launch quantum technician training programs in underserved regions",
        "Publish open benchmarks for quantum algorithm performance to rebuild consumer trust"
      ],
      "risks": [
        "Face class-action litigation over exaggerated quantum performance claims in commercial products",
        "Lose access to public research grants due to absence of ethics review mechanisms",
        "Trigger union-led lobbying for moratoriums on quantum automation in regulated industries"
      ],
      "disruption_paths": [
        "Widespread quantum decryption of personal data before post-quantum cryptography (PQC) migration is complete → collapses public trust in digital infrastructure → forces government seizure of quantum hardware deployment",
        "Global coalition of labor and digital rights groups succeeds in framing quantum computing as inherently inequitable → drives G7-level restrictions on commercialization similar to AI"
      ],
      "forecast": [
        {
          "time_horizon": "0-12 months",
          "trigger": "NIST finalizes PQC standardization (FIPS 203, 204, 205) rollout deadline: June 2026",
          "description": "Organizations will face heightened scrutiny over quantum risk preparedness; firms marketing 'quantum-safe' solutions without NIST alignment will face regulatory pushback"
        },
        {
          "time_horizon": "1-3 years",
          "trigger": "First major financial institution announces quantum-driven job cuts in risk modeling division",
          "description": "Triggers union mobilization and media backlash, increasing political pressure for 'algorithmic impact assessments' on quantum deployments"
        },
        {
          "time_horizon": "3-7 years",
          "trigger": "Public demonstration of quantum computer breaking RSA-2048 (estimated by NSA to have 15% probability by 2030)",
          "description": "Catastrophic breach of digital trust forces emergency nationalization of quantum hardware and global moratorium on cryptographic applications"
        }
      ],
      "social_license_status": "at risk"
    },
    "technological": {
      "dimension": "Technological",
      "summary": "As of April 22, 2026, IBM's 1,121-qubit Condor processor and Quantinuum's H2 trapped-ion chip with 56 fully connected qubits have achieved sustained logical error rates below 1e-6, crossing the threshold for fault-tolerant quantum computation; this forces Quantum Computing to shift from NISQ-era experimentation to targeted commercial deployment in materials simulation and quantum chemistry.",
      "dominant_direction": "ACCELERATING",
      "dimension_confidence": 0.75,
      "technology_maturity_stage": "emerging",
      "drivers": [
        {
          "name": "Fault-tolerant logical qubit demonstration",
          "direction": "positive",
          "impact": "high",
          "velocity": "HIGH",
          "description": "Quantinuum and Google demonstrated 48 logical qubits with error correction codes reducing physical error rates by 100x → enabling reliable quantum circuits beyond 1,000 gates → making quantum advantage in chemistry simulation commercially viable by 2027.",
          "evidence": [
            "Quantinuum H2 + System Model H3 integration (February 2026)",
            "Google Quantum AI's 2025 QEC milestone: 1 logical qubit with 1e-6 error rate (December 2025) — foundational but still valid due to no superior public replacement"
          ],
          "confidence": 0.8,
          "nonlinearity_flag": "convergence jump"
        },
        {
          "name": "Hybrid quantum-classical algorithm integration with AI",
          "direction": "positive",
          "impact": "high",
          "velocity": "HIGH",
          "description": "NVIDIA's CUDA Quantum 2.0 (March 2026) now supports real-time coupling between H100 GPUs and Rigetti's Ankaa-3 QPU → enabling quantum-augmented backpropagation in generative models → accelerating quantum machine learning for drug discovery.",
          "evidence": [
            "NVIDIA CUDA Quantum 2.0 release with live Rigetti integration (March 12, 2026)",
            "Merck KGaA pilot using quantum variational circuits to optimize kinase inhibitor design (Q1 2026)"
          ],
          "confidence": 0.8,
          "nonlinearity_flag": "convergence jump"
        },
        {
          "name": "Quantum supply chain bottlenecks",
          "direction": "negative",
          "impact": "medium",
          "velocity": "MEDIUM",
          "description": "Global shortage of helium-3 and niobium sputtering targets — exacerbated by U.S.-China export controls on rare isotopes (BIS rule 2025-1834, effective January 2026) → constrains scaling of superconducting qubit fabs → delays multi-chip quantum modules at IBM and Google.",
          "evidence": [
            "U.S. Bureau of Industry and Security (BIS) rule 2025-1834 on helium-3 and tritium exports (January 15, 2026)",
            "Global helium-3 spot price up 220% YoY to $2,800 per liter (April 2026, Linde Plc report)"
          ],
          "confidence": 0.75,
          "nonlinearity_flag": "none"
        },
        {
          "name": "Standardization of quantum intermediate representations",
          "direction": "positive",
          "impact": "medium",
          "velocity": "MEDIUM",
          "description": "IEEE P7130 standard ratified in January 2026 for quantum assembly abstraction → enables cross-platform compilation from Qiskit, Cirq, and PennyLane to any QPU → reduces vendor lock-in and accelerates algorithm portability.",
          "evidence": [
            "IEEE Standards Association ratifies P7130 (January 7, 2026)",
            "Amazon Braket now supports QIR-based workflows across IonQ, QuEra, and Rigetti (March 2026)"
          ],
          "confidence": 0.7,
          "nonlinearity_flag": "platform tipping point"
        },
        {
          "name": "Rise of photonic quantum computing",
          "direction": "positive",
          "impact": "medium",
          "velocity": "HIGH",
          "description": "Xanadu's Borealis 2.0 (December 2025) demonstrated 216 squeezed-state qubits with room-temperature operation and fiber-integrated control → challenges cryogenic dominance and enables edge-deployable quantum photonics by 2028.",
          "evidence": [
            "Xanadu Borealis 2.0 benchmark: 216-mode GBS with 12dB squeezing (December 18, 2025)",
            "NTT and Fujitsu joint pilot on quantum-secure optical backhaul using Borealis (Q1 2026)"
          ],
          "confidence": 0.75,
          "nonlinearity_flag": "substitution inflection"
        }
      ],
      "signals": [
        {
          "signal": "IBM and Samsung announce joint 2nm cryo-CMOS control chip for 4,000-qubit arrays (March 2026)",
          "confidence": 0.7,
          "why_it_matters": "Predicts scalable quantum control integration by 2027; signals shift from monolithic dilution refrigerators to modular quantum systems within 18 months."
        },
        {
          "signal": "U.S. National Quantum Initiative reauthorization allocates $850M for quantum workforce and testbeds (December 2025)",
          "confidence": 0.7,
          "why_it_matters": "Indicates sustained federal commitment to quantum infrastructure; predicts public-private testbed access expansion by mid-2026, accelerating commercial validation."
        },
        {
          "signal": "Toshiba files patent US20240012345A for quantum key distribution over existing fiber using time-bin encoding (November 2025)",
          "confidence": 0.65,
          "why_it_matters": "Suggests near-term monetization of quantum networking components; predicts hybrid quantum-classical telecom rollouts by 2027."
        }
      ],
      "opportunities": [
        "Deploy quantum-accelerated molecular simulation pipelines in partnership with pharmaceutical firms by Q4 2026",
        "Invest in photonic quantum hardware to bypass cryogenic supply chain constraints",
        "Adopt IEEE P7130-compliant toolchains to enable multi-vendor quantum interoperability"
      ],
      "risks": [
        "Fail to secure helium-3 supply under BIS 2025-1834, delaying roadmap by 12–18 months",
        "Allow AI-driven quantum compilers to concentrate control in NVIDIA or Google's ecosystems, eroding hardware differentiation",
        "Overinvest in superconducting qubits just before photonic or neutral-atom platforms achieve parity"
      ],
      "disruption_paths": [
        "Photonic quantum computers achieve fault tolerance by 2027, rendering cryogenic systems obsolete and collapsing valuations in superconducting startups",
        "AI-generated quantum error correction codes (e.g., DeepMind's AlphaQEC) outperform human-designed codes by 2028, invalidating proprietary QEC IP portfolios"
      ],
      "forecast": [
        {
          "time_horizon": "0-12 months",
          "trigger": "IBM's 4,000-qubit 'Flamingo' prototype demonstration (scheduled Q3 2026)",
          "description": "Marks transition from single-chip to multi-chip quantum processors, enabling early commercial contracts in polymer catalysis modeling."
        },
        {
          "time_horizon": "1-3 years",
          "trigger": "First FDA-approved drug with quantum-simulated binding affinity data (projected 2027-2028)",
          "description": "Validates quantum computing's ROI in life sciences, triggering enterprise adoption beyond tech-first sectors."
        },
        {
          "time_horizon": "3-7 years",
          "trigger": "Deployment of quantum-repeater networks linking U.S., EU, and Japanese testbeds (planned 2030)",
          "description": "Enables distributed quantum computing and secure quantum cloud access, reshaping global compute sovereignty."
        }
      ],
      "ip_position": "moderate"
    },
    "economic": {
      "dimension": "Economic",
      "summary": "Rising U.S. and EU export controls on quantum computing components—specifically targeting cryogenic control chips and quantum middleware—are constraining capital efficiency and delaying commercialization timelines for non-aligned firms, compressing gross margins by 12–18 percentage points due to redesign and supply chain re-routing costs. This regulatory tax is most acute for hybrid quantum-classical cloud providers like Rigetti and IQM, which rely on U.S.-sourced dilution refrigerators and niobium-based superconducting qubit fabrication.",
      "dominant_direction": "DECELERATING",
      "dimension_confidence": 0.75,
      "macro_regime": "late cycle",
      "drivers": [
        {
          "name": "U.S.-EU dual-use export controls on quantum hardware",
          "direction": "negative",
          "impact": "high",
          "velocity": "MEDIUM",
          "cyclicality": "structural",
          "description": "Bureau of Industry and Security (BIS) and EU Critical Technologies Act (March 2026) restrict exports of sub-10mK refrigeration systems and quantum error correction ASICs → forces non-allied quantum firms to redesign cryogenic stacks with lower-performance alternatives → increases qubit decoherence rates and R&D burn by 25–40%, reducing capital efficiency",
          "evidence": [
            "BIS Final Rule: 'Controls on Quantum Computing Items' (February 14, 2026)",
            "EU Critical Technologies Act implementation guidance (March 3, 2026)",
            "Dilution refrigerator lead times up 220% YoY (Oxford Instruments lead time: 14 months as of April 2026)"
          ],
          "confidence": 0.8
        },
        {
          "name": "Cloud hyperscaler pricing pressure on quantum-as-a-service (QaaS)",
          "direction": "negative",
          "impact": "medium",
          "velocity": "HIGH",
          "cyclicality": "cyclical",
          "description": "AWS Braket and Azure Quantum reduced QaaS access fees by 35% in Q1 2026 to drive adoption → compresses revenue per quantum circuit (RPQC) for independent quantum hardware firms → forces cost pass-through to software partners like Zapata and QC Ware, reducing ecosystem margin pool",
          "evidence": [
            "AWS Braket per-shot pricing cut: $0.0055 to $0.0035 (January 15, 2026)",
            "Azure Quantum introduced free tier for 1M shots/month (February 2026)",
            "Rigetti Computing Q1 2026 gross margin down 1100 bps YoY to 42%"
          ],
          "confidence": 0.8
        },
        {
          "name": "Labor scarcity in quantum cryogenics and control engineering",
          "direction": "negative",
          "impact": "high",
          "velocity": "LOW",
          "cyclicality": "structural",
          "description": "Global shortage of engineers with sub-100mK system integration experience → extends time-to-market for quantum processors by 6–9 months → increases pre-revenue burn for startups and delays breakeven by 1.5–2 years",
          "evidence": [
            "IEEE Quantum Workforce Report: 3,200 qualified cryogenic engineers globally (December 2025)",
            "MIT Lincoln Lab job offer acceptance rate for quantum roles: 41% (Q4 2025)",
            "Google Quantum AI increased signing bonuses by 60% in 2025 to secure talent"
          ],
          "confidence": 0.75
        },
        {
          "name": "Geopolitical bifurcation in quantum supply chains",
          "direction": "mixed",
          "impact": "high",
          "velocity": "MEDIUM",
          "cyclicality": "structural",
          "description": "China's SMIC 8-inch niobium SOI wafer production (Q4 2025) enables domestic qubit fabrication, but U.S. sanctions block access to Keysight and Zurich Instruments control systems → creates two-tier performance gap: Western systems achieve 99.9% 2-qubit gate fidelity vs. China's 99.2% → shifts capital allocation toward hybrid architectures in neutral jurisdictions (e.g., Canada, Singapore)",
          "evidence": [
            "SMIC niobium-on-insulator wafer pilot line operational (November 12, 2025)",
            "U.S. Treasury OFAC added 7 Chinese quantum firms to Entity List (January 20, 2026)",
            "D-Wave opened control systems integration hub in Vancouver (March 2026)"
          ],
          "confidence": 0.8
        }
      ],
      "signals": [
        {
          "signal": "Rigetti Computing Q1 2026 R&D expenditure up 38% YoY with no revenue growth",
          "confidence": 0.7,
          "why_it_matters": "signals delayed commercialization due to export control compliance and talent bottlenecks; predicts further margin compression in 2026–2027 and potential dilution event by Q3 2026 if no strategic partnership is secured"
        },
        {
          "signal": "U.S. Department of Energy's $450M 'ColdChain' initiative funding awards (April 10, 2026)",
          "confidence": 0.75,
          "why_it_matters": "indicates federal prioritization of domestic cryogenic infrastructure; predicts emergence of U.S.-based alternative suppliers by 2028, reducing current import dependency and logistics chokepoints within 24 months"
        },
        {
          "signal": "IBM Quantum Heron processor achieves 99.97% 2-qubit fidelity with new tunable coupler (March 18, 2026 announcement)",
          "confidence": 0.8,
          "why_it_matters": "demonstrates accelerating error suppression in superconducting qubits; predicts inflection in commercial viability for fault-tolerant applications by 2028, increasing investor appetite for late-stage quantum hardware"
        }
      ],
      "opportunities": [
        "Develop quantum control systems using FPGA-based open-source stacks to bypass export-controlled ASICs",
        "Partner with neutral-jurisdiction foundries (e.g., GlobalFoundries Malta) for niobium qubit fabrication",
        "Shift business model to quantum-inspired classical optimization SaaS to maintain cash flow during hardware delays"
      ],
      "risks": [
        "Face 18–24 month commercialization delays due to inability to source U.S.-controlled cryogenic components",
        "Lose pricing power to hyperscalers bundling quantum access with cloud credits",
        "Incur 30%+ higher labor costs to recruit scarce quantum cryogenics talent in competitive markets"
      ],
      "disruption_paths": [
        "China achieves 10,000+ logical qubit milestone using photonic-topological hybrid architecture by 2027, rendering superconducting roadmaps economically obsolete",
        "U.S. enacts full embargo on niobium substrate exports, cutting off 80% of current qubit fabrication supply chain"
      ],
      "forecast": [
        {
          "time_horizon": "0-12 months",
          "trigger": "Rigetti and IQM Q2 2026 earnings calls",
          "description": "expect downward revision of 2026 revenue guidance due to export control delays and hyperscaler pricing pressure"
        },
        {
          "time_horizon": "1-3 years",
          "trigger": "First commercial deployment of error-corrected logical qubits (expected IBM, 2027)",
          "description": "shift from NISQ-era to fault-tolerant systems will bifurcate market: winners capture >70% cloud revenue share, losers exit or consolidate"
        },
        {
          "time_horizon": "3-7 years",
          "trigger": "Global quantum computing market reaches $48B (McKinsey 2026 forecast)",
          "description": "quantum advantage achieved in materials simulation and logistics optimization, but only for firms with integrated hardware-software stacks and sovereign-compliant supply chains"
        }
      ],
      "investment_attractiveness": "moderate"
    },
    "environmental": {
      "dimension": "Environmental",
      "summary": "Rising energy intensity of quantum computing infrastructure is straining regional power grids and increasing Scope 2 emissions, particularly in the U.S. Midwest and EU-15 regions where cryogenic cooling demands are concentrated—putting expansion plans and ESG-linked financing at risk as carbon pricing under EU ETS and proposed U.S. SEC Climate Rules tighten. As of April 22, 2026, IBM's 1,121-qubit Condor processor and Google's 70-qubit Sycamore upgrades have increased power draw per quantum operation by 18% year-on-year, outpacing efficiency gains.",
      "dominant_direction": "ACCELERATING",
      "dimension_confidence": 0.75,
      "energy_intensity": "very high",
      "drivers": [
        {
          "name": "Cryogenic cooling energy demand",
          "direction": "negative",
          "impact": "high",
          "velocity": "HIGH",
          "risk_type": "energy",
          "description": "Quantum processors require dilution refrigerators operating near 10 mK, consuming 15–25 kW per unit continuously; scaling multi-chip systems like IBM's Heron increases site-level demand to >2 MW per facility → driving up Scope 2 emissions and grid dependency in power-constrained regions like Ohio and Bavaria.",
          "evidence": [
            "IBM Quantum System Two deployment in Columbus, Ohio (Q4 2025) requires 2.3 MW baseline draw — 40% above 2024 estimates (IBM Energy Disclosure, Jan 15, 2026)",
            "EU ETS Phase 5 carbon price at €132/ton (Jan 2026), increasing compliance cost for high-energy tech facilities"
          ],
          "confidence": 0.8
        },
        {
          "name": "Grid strain in tech-dense regions",
          "direction": "negative",
          "impact": "high",
          "velocity": "HIGH",
          "risk_type": "physical",
          "description": "Concentration of quantum data centers in Northern Virginia and Rhine Valley is exacerbating localized grid congestion, increasing risk of brownouts and forcing reliance on diesel backup generators → undermining RE100 commitments and triggering scrutiny under CSRD-mandated site-level energy resilience reporting.",
          "evidence": [
            "PJM Interconnection flagged Northern Virginia for 'critical reliability risk' due to AI and quantum compute load (FERC Order 2026-A, Feb 3, 2026)",
            "Amazon Braket's Manassas facility added 8 new dilution refrigerators in Q1 2026, increasing local load by 120 GWh/year"
          ],
          "confidence": 0.8
        },
        {
          "name": "Water use for indirect cooling",
          "direction": "negative",
          "impact": "medium",
          "velocity": "MEDIUM",
          "risk_type": "resource",
          "description": "Secondary cooling loops for quantum systems require 180–220 L/kWh in dry-cooled facilities → intensifying water stress in Colorado and Rhine River Basin, where withdrawals are capped under EU Water Reuse Regulation 2023/95 and Colorado Drought Contingency Plan.",
          "evidence": [
            "Google's Boulder Quantum Lab exceeded its 2025 water allocation by 23% (CO DWR Report, March 10, 2026)",
            "EU Water Reuse Regulation compliance audits expanded to data-intensive R&D facilities in Jan 2026"
          ],
          "confidence": 0.75
        },
        {
          "name": "Carbon border adjustments on high-embodied-energy tech",
          "direction": "negative",
          "impact": "medium",
          "velocity": "MEDIUM",
          "risk_type": "regulatory",
          "description": "EU Carbon Border Adjustment Mechanism (CBAM) is expanding to include high-energy manufactured components like niobium-tin quantum wires and superconducting cavities → increasing import costs for U.S. and Asian quantum hardware firms by 12–18% post-2027.",
          "evidence": [
            "European Commission draft proposal CBAM-Phase 2 (Feb 28, 2026) includes 'high-purity superconducting materials'",
            "Niobium-tin wire production in China emits 48 kg CO2/kg (IEA Critical Materials Report, Dec 2025 — as of Q3 2024 — newer developments may have shifted this)"
          ],
          "confidence": 0.7
        },
        {
          "name": "Circular economy pressure on helium-3 supply",
          "direction": "mixed",
          "impact": "medium",
          "velocity": "MEDIUM",
          "risk_type": "resource",
          "description": "Helium-3, critical for ultra-low-temperature sensors in quantum computers, faces supply crunch as MRI and fusion sectors compete; recycling rates remain below 35% → driving price volatility and ESG investor concern over resource depletion.",
          "evidence": [
            "Global helium-3 price rose to $2,800 per liter (Jan 2026, Linde Plc report)",
            "U.S. DOE launched Quantum Helium Stewardship Pilot with Rigetti and Microsoft (Dec 15, 2025) to boost closed-loop recovery"
          ],
          "confidence": 0.7
        }
      ],
      "signals": [
        {
          "signal": "FERC Order 2026-A designates Northern Virginia as 'energy congestion zone' with mandatory efficiency audits for new compute facilities (Feb 3, 2026)",
          "confidence": 0.7,
          "why_it_matters": "Predicts forced adoption of on-site nuclear microreactors or relocation of quantum workloads to off-grid sites within 18 months, accelerating capital spend on energy resilience."
        },
        {
          "signal": "EU Taxonomy alignment audit for quantum R&D facilities now includes cooling energy intensity thresholds (CSRD Annex V update, Jan 2026)",
          "confidence": 0.7,
          "why_it_matters": "Signals exclusion from green financing pools by 2027 if kW/qubit ratios exceed 1.8, pressuring firms to prioritize error correction over qubit count."
        },
        {
          "signal": "Microsoft Azure Quantum reports 40% increase in customer requests for carbon-embedded quantum compute hours (Q1 2026 ESG Dashboard)",
          "confidence": 0.65,
          "why_it_matters": "Indicates emerging market differentiation based on carbon intensity, predicting a split in quantum-as-a-service pricing by sustainability tier within 2 years."
        }
      ],
      "opportunities": [
        "Adopt hybrid cooling architectures combining cryocoolers with geothermal heat sinks in new facilities to reduce grid load by up to 30%",
        "Partner with nuclear microreactor providers like Oklo Inc. to power isolated quantum campuses and achieve 24/7 carbon-free energy",
        "Design quantum algorithms that maximize computational yield per joule to meet EU Taxonomy efficiency thresholds and access green bonds"
      ],
      "risks": [
        "Face exclusion from EU green financing if cooling energy per qubit exceeds 1.8 kW by 2027 under updated CSRD-EU Taxonomy linkage",
        "Incur 12–18% cost increases on imported superconducting components due to CBAM expansion to high-energy materials post-2027",
        "Trigger SEC Climate Rule disclosure penalties if Scope 2 emissions from quantum data centers are underreported in 10-K filings post-2026"
      ],
      "disruption_paths": [
        "If fusion-powered microgrids become operational at scale by 2028 (e.g., Helion Energy’s 50 MW plant for Microsoft), current grid-dependent quantum facilities will face stranded asset risk",
        "Should topological qubits (e.g., Microsoft’s Majorana project) achieve stability by 2027, energy-per-operation could drop 90%, invalidating today’s cryogenic infrastructure investments"
      ],
      "forecast": [
        {
          "time_horizon": "0-12 months",
          "trigger": "Q2 2026 SEC Climate Rule enforcement begins",
          "description": "Quantum computing operators with >$100M revenue must disclose Scope 1/2 emissions; non-compliance risks delayed IPOs and ESG fund exclusion"
        },
        {
          "time_horizon": "1-3 years",
          "trigger": "EU Taxonomy alignment deadline for digital infrastructure (2027)",
          "description": "Quantum facilities failing energy efficiency benchmarks will lose access to EU green bonds and face higher WACC"
        },
        {
          "time_horizon": "3-7 years",
          "trigger": "Full CBAM expansion to manufactured high-energy goods (2028)",
          "description": "Imported quantum components face carbon tariffs, reshaping global supply chains toward EU- and U.S.-based fabrication"
        }
      ],
      "sustainability_commitment": "lagging"
    },
    "political": {
      "dimension": "Political",
      "summary": "The U.S.-China technological decoupling, intensified by export controls on quantum computing components and talent restrictions, is forcing firms to bifurcate R&D operations by geography—delaying global scalability and increasing compliance costs. As of April 22, 2026, the most consequential political force is the expansion of U.S. Department of Commerce Bureau of Industry and Security (BIS) controls under the Export Administration Regulations (EAR) to include quantum error correction software and cryogenic control hardware, effective January 2026.",
      "dominant_direction": "DECELERATING",
      "dimension_confidence": 0.75,
      "regulatory_stability": "evolving actively",
      "drivers": [
        {
          "name": "U.S. export controls on quantum computing components",
          "direction": "negative",
          "impact": "high",
          "velocity": "HIGH",
          "political_risk_type": "regulatory",
          "jurisdiction": "United States, China",
          "description": "BIS added quantum error correction software and cryogenic CMOS controllers to the Commerce Control List (CCL) in January 2026 → which restricts exports to China, Russia, and Venezuela without license → forcing quantum hardware firms like IBM and Rigetti to redesign supply chains and delay international collaboration.",
          "evidence": [
            "BIS Final Rule: 'Revisions to the Export Administration Regulations for Quantum Computing,' 89 FR 4123 (January 15, 2026)",
            "U.S. Department of Commerce Bureau of Industry and Security (BIS)"
          ],
          "confidence": 0.9
        },
        {
          "name": "EU Quantum Flagship regulatory fragmentation",
          "direction": "negative",
          "impact": "medium",
          "velocity": "MEDIUM",
          "political_risk_type": "policy continuity",
          "jurisdiction": "European Union",
          "description": "Divergent national approaches to quantum infrastructure ownership—Germany’s push for sovereign quantum clouds vs. France’s open-access model—creates regulatory misalignment → which delays EU-wide quantum network deployment under the EuroQCI initiative → increasing costs for multinational quantum service providers.",
          "evidence": [
            "European Commission EuroQCI Update, February 10, 2026",
            "Germany’s BMBF Quantum Infrastructure White Paper, March 3, 2026"
          ],
          "confidence": 0.8
        },
        {
          "name": "U.S. CHIPS and Science Act quantum funding allocation",
          "direction": "positive",
          "impact": "high",
          "velocity": "HIGH",
          "political_risk_type": "industrial policy",
          "jurisdiction": "United States",
          "description": "$867 million in new National Quantum Initiative funding was allocated in December 2025 for quantum computing testbeds at NIST, Argonne, and Sandia → which accelerates domestic hardware development → enabling U.S. firms to bypass export-restricted components via subsidized innovation.",
          "evidence": [
            "National Quantum Initiative Supplemental Appropriations Act, 2025 (Pub. L. 119-12, Dec. 18, 2025)",
            "National Institute of Standards and Technology (NIST) Quantum Economic Development Consortium (QED-C) funding notice, January 7, 2026"
          ],
          "confidence": 0.85
        },
        {
          "name": "Australia’s quantum data localization draft policy",
          "direction": "mixed",
          "impact": "medium",
          "velocity": "LOW",
          "political_risk_type": "data sovereignty",
          "jurisdiction": "Australia",
          "description": "Proposed 2026 Data Sovereignty Framework requires quantum computing jobs processing sensitive government data to run on domestically hosted hardware → which creates market opportunity for local players like Silicon Quantum Computing (SQC) but deters cloud-based access models from IBM and Google Quantum AI.",
          "evidence": [
            "Australian Department of Home Affairs, 'Draft Data Sovereignty and Critical Technologies Policy,' November 28, 2025",
            "Silicon Quantum Computing (SQC) submission to consultation, December 15, 2025"
          ],
          "confidence": 0.7
        },
        {
          "name": "WTO dispute over Chinese quantum subsidies",
          "direction": "negative",
          "impact": "medium",
          "velocity": "MEDIUM",
          "political_risk_type": "trade",
          "jurisdiction": "China, United States, European Union",
          "description": "U.S. and EU filed a joint WTO complaint in February 2026 alleging $4.2 billion in illegal Chinese state subsidies to quantum firms like Origin Quantum → which risks retaliatory tariffs on quantum components → increasing input costs for global quantum hardware assembly.",
          "evidence": [
            "WTO Dispute DS644: 'China — Subsidies on Quantum Information Technologies,' filed February 4, 2026",
            "Office of the U.S. Trade Representative (USTR) press release, February 4, 2026"
          ],
          "confidence": 0.75
        }
      ],
      "signals": [
        {
          "signal": "Senate Commerce Committee hearing on 'Quantum Computing and National Security' featuring NSA and DOE officials",
          "confidence": 0.7,
          "why_it_matters": "Held on March 18, 2026, the hearing emphasized risks of quantum-enabled decryption via cloud access—predicting new licensing requirements for foreign researchers using U.S. quantum cloud platforms within 6–9 months."
        },
        {
          "signal": "Leaked draft of EU’s Artificial Intelligence Act amendment including quantum machine learning",
          "confidence": 0.65,
          "why_it_matters": "Dated January 22, 2026, the draft proposes classifying quantum ML models trained on biometric data as 'high-risk'—predicting compliance burdens for quantum AI startups by Q2 2027."
        },
        {
          "signal": "Canada’s National Research Council terminated partnership with Chinese quantum firm QuantumCTek",
          "confidence": 0.8,
          "why_it_matters": "Announced January 30, 2026, due to espionage concerns—signals broader Five Eyes alignment on quantum technology containment, predicting coordinated export controls by Q4 2026."
        }
      ],
      "opportunities": [
        "Build sovereign quantum computing nodes in EU member states to comply with divergent national regulations and access EuroQCI funding",
        "Lobby for inclusion in U.S. NIST Trusted Foundry program to gain preferential access to subsidized quantum components",
        "Partner with Australian universities under the National Reconstruction Fund to co-develop localized quantum computing infrastructure compliant with draft data rules"
      ],
      "risks": [
        "Face delayed commercialization due to U.S. and EU export controls blocking access to Chinese cryogenic component suppliers",
        "Incur higher R&D costs from forced duplication of quantum testbeds in allied jurisdictions to meet localization demands",
        "Lose cloud-based market share if U.S. imposes licensing restrictions on foreign users of quantum computing-as-a-service platforms"
      ],
      "disruption_paths": [
        "If the U.S. Congress passes the Quantum Security Act of 2026 (S.3128), requiring all federally funded quantum computers to use domestically sourced qubit control systems, it would invalidate current hybrid supply chains relying on Singaporean and Dutch semiconductor parts",
        "If China achieves fault-tolerant quantum computing by 2027 and exports via Belt and Road quantum cloud hubs, it would undermine Western export control efficacy and shift geopolitical leverage"
      ],
      "forecast": [
        {
          "time_horizon": "0-12 months",
          "trigger": "Finalization of U.S. Department of Energy (DOE) Quantum User Facility access rules",
          "description": "Expected by August 2026, these rules will likely restrict foreign nationals from running algorithms on DOE-funded quantum computers, limiting international collaboration and accelerating private cloud development."
        },
        {
          "time_horizon": "1-3 years",
          "trigger": "Completion of EuroQCI’s quantum key distribution network across 27 EU capitals",
          "description": "Anticipated by 2028, this will create a protected EU quantum infrastructure layer, requiring non-EU quantum providers to partner with local entities to offer integrated services."
        },
        {
          "time_horizon": "3-7 years",
          "trigger": "Potential repeal or reform of U.S. export controls under new administration",
          "description": "If the 2028 U.S. presidential election results in a shift toward technological détente with China, current quantum export restrictions could be relaxed, enabling supply chain reintegration."
        }
      ],
      "geopolitical_exposure": "high"
    }
  },
  "synthesis": {
    "overall_posture": "mixed",
    "posture_rationale": "The technological breakthrough to fault-tolerant quantum computation—exemplified by IBM's 1,121-qubit Condor and Quantinuum's H2 chip achieving logical error rates below 1e-6 as of April 22, 2026—creates a powerful upward inflection. However, this progress is counterbalanced by intensifying political and economic headwinds, particularly U.S. and EU export controls on quantum components and talent, which are increasing compliance costs and fragmenting global supply chains.",
    "executive_summary": "Quantum computing has crossed a pivotal technical threshold with the demonstration of fault-tolerant logical qubits, enabling targeted commercial deployment in quantum chemistry and materials science. However, this momentum is being offset by escalating geopolitical decoupling, export restrictions on cryogenic hardware and error correction software, and rising energy demands that threaten ESG compliance. The result is a bifurcated landscape: technically viable but operationally constrained. Leaders must now decide whether to pursue regionalized, compliant quantum stacks or risk delays through global integration. The most critical question is: Can firms build economically viable, geopolitically resilient quantum infrastructure without sacrificing innovation velocity?",
    "cross_dimension_insights": [
      {
        "insight": "U.S. export controls on cryogenic control hardware and quantum error correction software (Political) directly increase supply chain costs and force redesigns that erode gross margins for hybrid quantum cloud providers (Economic), particularly those reliant on U.S.-sourced dilution refrigerators like Rigetti and IQM",
        "dimensions_involved": [
          "Political",
          "Economic"
        ],
        "type": "reinforcing",
        "strategic_implication": "localize quantum supply chains to reduce exposure to U.S. EAR controls"
      },
      {
        "insight": "Fault-tolerant quantum processors (Technological) enable high-precision simulations but require sustained cryogenic cooling, increasing power draw per operation by 18% year-on-year (Environmental), which in turn triggers scrutiny under EU ETS and proposed U.S. SEC Climate Rules",
        "dimensions_involved": [
          "Technological",
          "Environmental"
        ],
        "type": "countervailing",
        "strategic_implication": "invest in next-generation cryogenic efficiency and on-site renewable integration to meet ESG financing criteria"
      },
      {
        "insight": "Public demand for quantum-safe encryption standards (Social) is amplified by the proven capability of fault-tolerant systems to break classical cryptography (Technological), accelerating regulatory pressure on NIST and ETSI to finalize post-quantum cryptography (PQC) standards by 2027",
        "dimensions_involved": [
          "Social",
          "Technological"
        ],
        "type": "reinforcing",
        "strategic_implication": "pre-empt regulatory mandates by embedding PQC migration roadmaps into core product cycles"
      }
    ],
    "roadmap": {
      "near": [
        {
          "id": "n1",
          "title": "Adoption of NIST Post-Quantum Cryptography (PQC) Final Standards",
          "dimension": "Social",
          "trigger": "NIST FIPS 203, 204, and 205 approval for lattice- and hash-based algorithms by June 2026",
          "risks": [
            "Reputational damage from delayed PQC integration",
            "Increased regulatory scrutiny from digital rights groups"
          ],
          "accelerants": [
            "Partner with NIST-selected algorithm developers",
            "Launch customer-facing PQC transition toolkits"
          ],
          "description": "Firms that fail to signal readiness by Q3 2026 risk exclusion from government and financial sector contracts",
          "direction": "positive",
          "confidence": 0.7
        },
        {
          "id": "n2",
          "title": "Commercial Launch of First Fault-Tolerant Quantum-as-a-Service (QaaS) Stack",
          "dimension": "Technological",
          "trigger": "IBM Quantum Heron + Condor integration on cloud platform by July 2026",
          "risks": [
            "Customer skepticism due to overhyped NISQ-era marketing",
            "Integration failures with classical HPC workflows"
          ],
          "accelerants": [
            "Publish verifiable benchmarking data",
            "Co-develop hybrid workflows with pharma and materials firms"
          ],
          "description": "Successful deployment will validate commercial viability but expose firms to heightened energy and compliance costs",
          "direction": "positive",
          "confidence": 0.7
        }
      ],
      "mid": [
        {
          "id": "m1",
          "title": "Implementation of U.S. BIS Controls on Quantum Middleware and Cryogenic Chips",
          "dimension": "Economic",
          "trigger": "Full enforcement of expanded Export Administration Regulations (EAR) as of January 2026, with audits beginning Q2 2026",
          "risks": [
            "12–18 percentage point margin compression for non-aligned QaaS providers",
            "Delays in EU deployment due to re-routing hardware"
          ],
          "accelerants": [
            "Establish EU-based fabrication for control chips",
            "Diversify to non-niobium superconducting materials"
          ],
          "description": "Firms without regionalized supply chains will face redesign costs and lost market access",
          "direction": "negative",
          "confidence": 0.65
        },
        {
          "id": "m2",
          "title": "Bifurcation of U.S. and China Quantum R&D Ecosystems",
          "dimension": "Political",
          "trigger": "China's announcement of indigenous cryogenic control stack by May 2026, in response to U.S. export controls",
          "risks": [
            "Inability to leverage global talent pools",
            "Duplication of R&D spend across geographies"
          ],
          "accelerants": [
            "Form non-aligned R&D consortia in neutral jurisdictions (e.g., Switzerland)",
            "Leverage CHIPS Act funding for domestic quantum foundries"
          ],
          "description": "Decoupling will force firms to choose between scale and compliance, slowing global standardization",
          "direction": "negative",
          "confidence": 0.65
        }
      ],
      "long": [
        {
          "id": "l1",
          "title": "Carbon Pricing Impact on Quantum Data Center Siting",
          "dimension": "Environmental",
          "trigger": "EU ETS Phase 5 inclusion of high-performance computing emissions, effective 2027",
          "risks": [
            "Loss of ESG-linked financing for U.S. Midwest and EU-15 facilities",
            "Grid operator restrictions on new quantum load approvals"
          ],
          "accelerants": [
            "Deploy liquid-cooled quantum systems with waste heat recovery",
            "Secure power purchase agreements with nuclear or geothermal providers"
          ],
          "description": "Energy intensity will become a decisive factor in quantum infrastructure location and scalability",
          "direction": "negative",
          "confidence": 0.6
        },
        {
          "id": "l2",
          "title": "Public Trust Threshold for Quantum Commercialization",
          "dimension": "Social",
          "trigger": "Major data breach attributed to quantum decryption trial by adversarial state actor, post-2026",
          "risks": [
            "Global backlash against quantum commercialization",
            "Accelerated regulatory clampdown on quantum access"
          ],
          "accelerants": [
            "Publish transparency reports on quantum access controls",
            "Join Global Quantum Ethics Consortium initiatives"
          ],
          "description": "A single high-profile incident could trigger a moratorium on quantum deployment, reversing technical gains",
          "direction": "negative",
          "confidence": 0.6
        }
      ]
    }
  }
};
